name: 'Documentation Bot'
description: 'Automatically label pull requests based on the checked task list'
author: 'Max Xu <maxs.xu@gmail.com>'
branding:
  icon: 'check'
  color: 'green'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: apache/pulsar-test-infra
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Execute
      run: go run .
      shell: bash
      working-directory: docbot
